### ISSUE TITLE
what is this

### ISSUE THREAD

**Issue by FreshPenguin112** [Ianyourgod/whydoidothistomyselfugh#1]
what is this

**Comment by themysticsavages** [comment]
This looks like a language interpreter which tries to make an syntax tree from scratch (although not recommended 😖)

**Comment by Ianyourgod** [comment]
> This looks like a language interpreter which tries to make a syntax tree from scratch (although not recommended 😖)

Yes, but it’s also a copy of something I made a while ago. Basically, instead of fully using oop, I try to use just mainly strings and see what I can do from there.

**Comment by Ianyourgod** [comment]
:)
